//
// Generated file, do not edit! Created by opp_msgtool 6.3 from FlyingQubit.msg.
//

#ifndef __QUISP__MESSAGES_FLYINGQUBIT_M_H
#define __QUISP__MESSAGES_FLYINGQUBIT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace quisp {
namespace messages {

class FlyingQubit;

}  // namespace messages
}  // namespace quisp

// cplusplus {{
    #include <backends/interfaces/IQubit.h>
    using quisp::backends::abstract::IQubit;
// }}


namespace quisp {
namespace messages {

/**
 * Class generated from <tt>FlyingQubit.msg:14</tt> by opp_msgtool.
 * <pre>
 * message FlyingQubit
 * {
 *     string message_type = "qubit";
 *     IQubit *qubitRef;
 *     bool isFirst \@getter(isFirst) \@setter(setFirst) = false;
 *     bool isLast \@getter(isLast) \@setter(setLast) = false;
 * }
 * </pre>
 */
class FlyingQubit : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string message_type = "qubit";
    ::IQubit * qubitRef = nullptr;
    bool isFirst_ = false;
    bool isLast_ = false;

  private:
    void copy(const FlyingQubit& other);

  protected:
    bool operator==(const FlyingQubit&) = delete;

  public:
    FlyingQubit(const char *name=nullptr, short kind=0);
    FlyingQubit(const FlyingQubit& other);
    virtual ~FlyingQubit();
    FlyingQubit& operator=(const FlyingQubit& other);
    virtual FlyingQubit *dup() const override {return new FlyingQubit(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMessage_type() const;
    virtual void setMessage_type(const char * message_type);

    virtual const ::IQubit * getQubitRef() const;
    virtual ::IQubit * getQubitRefForUpdate() { return const_cast<::IQubit *>(const_cast<FlyingQubit*>(this)->getQubitRef());}
    virtual void setQubitRef(::IQubit * qubitRef);

    virtual bool isFirst() const;
    virtual void setFirst(bool isFirst);

    virtual bool isLast() const;
    virtual void setLast(bool isLast);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FlyingQubit& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FlyingQubit& obj) {obj.parsimUnpack(b);}


}  // namespace messages
}  // namespace quisp


namespace omnetpp {

inline any_ptr toAnyPtr(const IQubit *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline IQubit *fromAnyPtr(any_ptr ptr) { return ptr.get<IQubit>(); }
template<> inline quisp::messages::FlyingQubit *fromAnyPtr(any_ptr ptr) { return check_and_cast<quisp::messages::FlyingQubit*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __QUISP__MESSAGES_FLYINGQUBIT_M_H

